name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, test, publish
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - name: Build 00-simple
      working-directory: 00-simple
      run: |
        npm install
        node_modules/.bin/webpack
    - name: Build 01-api
      working-directory: 01-api
      run: |
        npm install
        npm run dev
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    - name: Build Hugo site
      run: |
        mkdir hugo/content
        cp -r 00-simple/dist hugo/content/00-simple
        cp -r 00-simple/images hugo/content/00-simple/
        cp -r 01-api/dist hugo/content/01-api
        cd hugo
        hugo new index.md
        cat ../README.md >> content/index.md
        hugo -D
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./hugo/public
